version: '3'

volumes:
  adverity_swapi_local_postgres_data: {}
  adverity_swapi_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: adverity_swapi_local_django
    container_name: adverity_swapi_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: adverity_swapi_production_postgres
    container_name: adverity_swapi_local_postgres
    volumes:
      - adverity_swapi_local_postgres_data:/var/lib/postgresql/data
      - adverity_swapi_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: adverity_swapi_local_docs
    container_name: adverity_swapi_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./adverity_swapi:/app/adverity_swapi:z
    ports:
      - "9000:9000"
    command: /start-docs
